qt.version = $config.libbuild2_qt_tests.qt

using qt.moc

if ($qt.version == 5)
  import libs = libQt5Core%lib{Qt5Core}
else
  import libs = libQt6Core%lib{Qt6Core}

# All of the project's source files.
#
# Put hxx{source} in ./source/ to test that subdirectories are handled
# correctly.
#
src = hxx{source/source sink nomoc} cxx{sink driver}

exe{driver}: $src automoc{driver} libue{QtCoreMeta}

# The automoc{} target scans its hxx{} and cxx{} prerequisites for Qt
# meta-object macros and runs moc on those that match.
#
# Note that the corresponding moc output targets (cxx{moc_*} and moc{*}) are
# not explicitly referred to anywhere but may be if necessary, as long as
# there are no prerequisites or they are compatible with the would-be
# synthesized dependency (first prerequisite is the input header/source file,
# etc).
#
automoc{driver}: $src libue{QtCoreMeta}

# Test that non-ad hoc generated source files are updated before the Qt
# meta-object macro scan is done. (The link rule only updates headers and ad
# hoc source files during match.)
#
cxx{sink}: in{sink}

# A generated header that does not contain any meta-object macros and, in
# particular, should be cleaned if the automoc{} target is cleaned directly.
#
hxx{nomoc}: in{nomoc}

libue{QtCoreMeta}: $libs

# Set the include path prefix.
#
qt.moc.options = -p automoc

cxx{source/moc_source}: qt.moc.options = -p automoc/source

cxx.poptions += "-I$out_root" "-I$src_root"
