qt.version = $config.libbuild2_qt_tests.qt

using qt.moc

if ($qt.version == 5)
  import libs = libQt5Core%lib{Qt5Core}
else
  import libs = libQt6Core%lib{Qt6Core}

exe{driver}: hxx{source sink} cxx{driver sink}  \
             automoc{driver}                    \
             libue{QtCoreMeta}

# The automoc{} target scans its hxx{} and cxx{} prerequisites for Qt
# meta-object macros and runs moc on those that match.
#
# Note that the corresponding moc output targets (cxx{moc_*} and moc{*}) are
# not explicitly referred to anywhere.
#
automoc{driver}: hxx{source sink} cxx{sink} libue{QtCoreMeta}

# Test that non-ad hoc generated source files are updated before the Qt
# meta-object macro scan is done. (The link rule only updates headers and ad
# hoc source files during match.)
#
cxx{sink}: in{sink}

libue{QtCoreMeta}: $libs

# Set the include path prefix.
#
qt.moc.options = -p automoc

cxx.poptions += "-I$out_root" "-I$src_root"
