qt.version = $config.libbuild2_qt_tests.qt

using qt.moc
using qt.rcc
using qt.uic

if ($qt.version == 5)
  import libs = libQt5Core%lib{Qt5Core}
else
  import libs = libQt6Core%lib{Qt6Core}

# Use RCC to generate a C++ header, a C++ source file, and an external
# resource (binary data).
#
# The header is included by driver.cxx, the source file is compiled and linked
# into the driver executable, and the external resource is loaded at run time.
#
# The driver tests that all of these resources are accessible.
#

exe{driver}: cxx{driver} $libs

# Driver executable: dependencies on the RCC outputs.
#
exe{driver}: hxx{qrc_foo} cxx{qrc_bar}        # Embedded resources.

exe{driver}: file{baz.rcc}: include = posthoc # External resource.

# RCC outputs: dependencies on their resource collection files and resources.
#
hxx{qrc_foo}: qrc{foo} file{foo.txt}

cxx{qrc_bar}: qrc{bar} file{bar.txt}

file{baz.rcc}: qrc{baz} file{baz.txt}
{
  qt.rcc.options = --binary
}

# Build options.
#
# $out_base is required to load the external resource.
#
# Use $representation() to ensure a trailing separator and also escape
# backslashes on Windows.
#
ob = $regex.replace($representation($out_base), '\\', '\\\\')
cxx.poptions += "-I$out_base" -DOUT_BASE="\"$ob\""
