qt.version = $config.libbuild2_qt_tests.qt

using qt.moc
using qt.rcc
using qt.uic

./:
% test
{{
  diag test $>
  echo ($qt.moc.build.loaded && $qt.rcc.build.loaded && $qt.uic.build.loaded) >>>?'true'
}}
